import type { Metadata } from "next";
import "./globals.css";
import { noto_sans, poppins } from "./utils/fonts";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import EmotionRegistry from "./components/providers/emotion-registry";

export const metadata: Metadata = {
  title: "Zone Next",
  description: "Generated by create Zone Next",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${noto_sans} ${poppins} bg-gray-100`}>
        <ToastContainer />
        <main>
          <EmotionRegistry>{children}</EmotionRegistry>
        </main>
      </body>
    </html>
  );
}
