import type { Metadata } from "next";
import "./globals.css";
import { noto_sans, poppins } from "./utils/fonts";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import EmotionRegistry from "./components/providers/emotion-registry";
import AuthProvider from "./components/providers/auth-context";
import { cn } from "./utils/helpers";

export const metadata: Metadata = {
  title: "Zone Next",
  description: "Generated by create Zone Next",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <html lang={locale}>
      <body
        className={cn(noto_sans, poppins, "bg-gray-100", {
          "font-noto_sans": locale === "my",
        })}
      >
        <ToastContainer />
        <main>
          <EmotionRegistry>
            <AuthProvider>{children}</AuthProvider>
          </EmotionRegistry>
        </main>
      </body>
    </html>
  );
}
